### ISSUE TITLE
Starting with 1.1.35, hangs after compilation but before onSuccess runs

### ISSUE THREAD

**Issue by cameront** [gilamran/tsc-watch#49]
running:
`tsc-watch --onSuccess "./scripts/start:dev.sh" --onFailure "echo 'Beep! Compilation Failed'"`

1.1.34
```
[3:40:54 PM] Starting compilation in watch mode...
[3:41:05 PM] Compilation complete. Watching for file changes.
+ ./scripts/db:migrate.sh
Local redis port 9089
+ migrate_cmd='node ./dist/src/migrate.js'
+ '[' -z '' ']'
...
```

1.1.35
```
[3:48:22 PM] Starting compilation in watch mode...
[3:48:32 PM] Compilation complete. Watching for file changes.
```
[hangs indefinitely, and server never starts]

OSX

**Comment by cameront** [comment]
When files are changed, I do see an incremental compile happening in 1.1.35
```
[3:58:49 PM] File change detected. Starting incremental compilation...
```
But onSuccess doesn't seem to run.

**Comment by gilamran** [comment]
Can you please provide a short example to reproduce this?
It's working on my builds...

**Comment by cameront** [comment]
I think it may have something to do with my `typescript` version = 2.8.3

**Comment by cameront** [comment]
typescript version 2.9.1 is the first version that seems to work with 1.1.36

test.ts
```
function f() {
  console.log('hello world');
}

f();
```

`./node_modules/.bin/tsc-watch foo.ts --onSuccess "echo good" --onFailure "echo bad"`

**Comment by gilamran** [comment]
@cameront, you are right as of version 1.1.33 I catch the output of typescript +2.9.1.
There should be no issues with upgrading to typescript 2.9.1 or even better, to the latest.
Or, if you insist, you can use a fixed version of `tsc-watch` 1.1.32.

I know that it's not ideal, but I'd rather support new versions of typescript.
If you can't upgrade your typescript nor set `tsc-watch` to version 1.1.32, let me know and I'll see what I can do...

**Comment by cameront** [comment]
Yeah, pinning to until we upgrade typescript is a fine workaround
